# Generated by Django 5.2.9 on 2026-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_author_institution'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE api_author ALTER COLUMN primary_cluster TYPE integer USING primary_cluster::integer;',
            reverse_sql='ALTER TABLE api_author ALTER COLUMN primary_cluster TYPE varchar(max_length) USING primary_cluster::varchar;',
        ),

        migrations.AlterField(
            model_name='author',
            name='primary_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
