# Generated by Django 5.2.9 on 2026-04-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_author_primary_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(help_text='Keywords from BERTopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_fetched_papers',
        ),
        migrations.RemoveField(
            model_name='author',
            name='primary_cluster',
        ),
        migrations.RemoveField(
            model_name='author',
            name='topic_profile',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors_text',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='cluster_label',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='entropy',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='fields_of_study',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='openalex_concepts',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='predicted_multi_labels',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='topic_distribution',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='topic_keywords',
        ),
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(blank=True, default='Thammasat University', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PaperTopicInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_distribution', models.JSONField(blank=True, null=True)),
                ('entropy', models.FloatField(blank=True, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_info', to='api.paper')),
                ('primary_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_papers', to='api.topic')),
                ('related_topics', models.ManyToManyField(blank=True, related_name='related_papers', to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTopicStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255)),
                ('total_papers', models.IntegerField(default=0)),
                ('total_citations', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topic')),
            ],
            options={
                'unique_together': {('faculty', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='CoAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('author_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to='api.author')),
                ('author_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='api.author')),
                ('shared_topics', models.ManyToManyField(blank=True, to='api.topic')),
            ],
            options={
                'unique_together': {('author_a', 'author_b')},
            },
        ),
        migrations.CreateModel(
            name='YearlyTopicStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('total_papers', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_stats', to='api.topic')),
            ],
            options={
                'unique_together': {('year', 'topic')},
            },
        ),
    ]
