# Generated by Django 5.2.9 on 2026-04-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_topic_remove_author_last_fetched_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertopicinteraction',
            name='predicted_multi_labels',
            field=models.JSONField(blank=True, help_text="List of predicted labels e.g. ['Topic 103: ...', 'Topic 33: ...']", null=True),
        ),
    ]
