import os
import json
import re
from tqdm import tqdm
import google.generativeai as genai
from django.core.management.base import BaseCommand
from api.models import Paper
from api.services.bertopic_service import BERTopicService 

class Command(BaseCommand):
    help = "Run BERTopic, auto-tune, and use Gemini LLM to generate human-readable topic names"

    def add_arguments(self, parser):
        parser.add_argument("--gemini_key", type=str, help="Gemini API Key for auto-naming topics")
        parser.add_argument("--auto_tune", action="store_true", help="Auto-tune the number of topics")

    def generate_llm_names(self, topic_model, docs_dict, api_key):
        if not api_key:
            self.stdout.write(self.style.WARNING("No Gemini API key provided. Falling back to default keywords."))
            return {}

        self.stdout.write(self.style.NOTICE("Calling Gemini LLM to generate topic names..."))
        genai.configure(api_key=api_key)
        
        model = genai.GenerativeModel('gemini-flash-latest') 
        
        topic_info = topic_model.get_topic_info()
        prompt = (
            "You are an expert academic researcher and librarian. "
            "I have a list of topics generated by a topic modeling algorithm from research papers. "
            "For each topic, I will provide the top 15 keywords and 3 representative paper titles. "
            "Your task is to create a concise, professional academic category name (2-5 words) for each topic. "
            "Respond ONLY with a valid JSON format mapping the Topic ID (string) to the generated name.\n"
            "Example: {\"0\": \"Clinical Stroke Management\", \"1\": \"Quantum Computing Algorithms\"}\n\n"
        )

        for _, row in topic_info.iterrows():
            topic_id = row['Topic']
            if topic_id == -1:
                continue 
            
            keywords = [word for word, _ in topic_model.get_topic(topic_id)][:15]
            rep_docs = topic_model.get_representative_docs(topic_id)
            titles = [doc[:150] + "..." for doc in rep_docs[:3]] if rep_docs else []

            prompt += f"Topic ID: {topic_id}\n"
            prompt += f"Keywords: {', '.join(keywords)}\n"
            prompt += f"Representative Titles: {titles}\n\n"

        try:
            response = model.generate_content(
                prompt,
                generation_config=genai.GenerationConfig(
                    response_mime_type="application/json"
                )
            )
            llm_mapping = json.loads(response.text)
            self.stdout.write(self.style.SUCCESS("LLM successfully generated topic names!"))
            return llm_mapping
            
        except Exception as e:
            self.stdout.write(self.style.ERROR(f"Failed to parse LLM response: {e}"))
            return {}

    def handle(self, *args, **options):
        auto_tune = options.get("auto_tune")
        gemini_key = options.get("gemini_key")

        self.stdout.write(self.style.NOTICE("1. Fetching papers from Database..."))
        papers = list(Paper.objects.exclude(abstract__isnull=True).exclude(abstract="").values('id', 'title', 'abstract'))
        
        if not papers:
            self.stdout.write(self.style.ERROR("No papers with abstracts found."))
            return

        docs = [f"{p['title']}. {p['abstract']}" for p in papers]
        paper_ids = [p['id'] for p in papers]

        self.stdout.write(self.style.NOTICE(f"2. Training BERTopic (via Service) on {len(docs)} documents..."))
        
        service = BERTopicService(
            n_topics="auto" if auto_tune else None,
            use_approx_dist=True,
            use_lemmatized_input=False
        )
        
        topics, probs = service.fit_transform(docs)
        
        topic_model = service.topic_model 

        self.stdout.write(self.style.NOTICE("3. Assigning LLM Names..."))
        llm_names = self.generate_llm_names(topic_model, docs, gemini_key)

        self.stdout.write(self.style.NOTICE("4. Updating Database..."))
        
        updated_count = 0
        for i, paper_id in enumerate(tqdm(paper_ids, desc="Saving to DB")):
            topic_id = topics[i]
            paper_prob = probs[i] if probs is not None else []

            if topic_id == -1:
                cluster_label = "Outlier / Noise"
            else:
                topic_str_id = str(topic_id)
                if topic_str_id in llm_names:
                    cluster_label = f"Topic {topic_id}: {llm_names[topic_str_id]}"
                else:
                    words = [word for word, _ in topic_model.get_topic(topic_id)][:5]
                    cluster_label = f"Topic {topic_id}: {', '.join(words)}"

            multi_labels = [cluster_label]
            if topic_id != -1 and len(paper_prob) > 0:
                for alt_topic_id, prob in enumerate(paper_prob):
                    if alt_topic_id != topic_id and prob > 0.15:
                        alt_str_id = str(alt_topic_id)
                        if alt_str_id in llm_names:
                            alt_label = f"Topic {alt_topic_id}: {llm_names[alt_str_id]}"
                        else:
                            alt_words = [word for word, _ in topic_model.get_topic(alt_topic_id)][:5]
                            alt_label = f"Topic {alt_topic_id}: {', '.join(alt_words)}"
                        multi_labels.append(alt_label)

            raw_keywords = []
            if topic_id != -1:
                raw_keywords = [word for word, _ in topic_model.get_topic(topic_id)][:10]

            Paper.objects.filter(id=paper_id).update(
                cluster_id=topic_id,
                cluster_label=cluster_label,
                predicted_multi_labels=multi_labels,
                topic_keywords=raw_keywords
            )
            updated_count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully clustered and updated {updated_count} papers!"))