version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: tu_papers_postgres
    restart: always
    environment:
      POSTGRES_DB: senior_project_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
