FROM python:3.11-slim

# 2. Environment Variables for Python in Docker
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Folder
WORKDIR /app

# RUN apt-get update && apt-get install -y gcc python3-dev && rm -rf /var/lib/apt/lists/*

# 4. Install Dependencies
COPY requirements-web.txt /app/

RUN pip install --no-cache-dir -r requirements-web.txt

# 5. Source Code
COPY . /app/

# 6. User (Non-root) for security

RUN adduser --disabled-password django-user

RUN chown -R django-user:django-user /app

USER django-user

# 7. 8000 (for Nginx)
EXPOSE 8000

# 8. Gunicorn (จำกัด Worker แค่ 1 ตัวเพื่อไม่ให้แย่ง RAM กับ Java)
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--threads", "2", "backend.wsgi:application"]