AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Senior Project - Research Analytics Dashboard API
  Serverless Django running on AWS Lambda

Parameters:
  DatabaseUrl:
    Type: String
    Description: NeonDB Connection String
  DjangoSecretKey:
    Type: String
    Description: Django Secret Key

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DJANGO_SETTINGS_MODULE: backend.settings
        DATABASE_URL: !Ref DatabaseUrl
        SECRET_KEY: !Ref DjangoSecretKey
        ALLOWED_HOSTS: "*"
        CORS_ALLOWED_ORIGINS: "https://academic-dashboard.thara-sritharadol.com"
        CSRF_TRUSTED_ORIGINS: "https://academic-dashboard.thara-sritharadol.com"
        DEBUG: "False"

Resources:
  DjangoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_adapter.handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
