import json
import logging
import google.generativeai as genai

logger = logging.getLogger(__name__)

class GeminiNamingService:
    def __init__(self, api_key):
        self.api_key = api_key
        if self.api_key:
            genai.configure(api_key=self.api_key)
            self.model = genai.GenerativeModel('gemini-flash-latest') #

    def generate_topic_names(self, topic_model):
        if not self.api_key:
            logger.warning("No Gemini API key provided. Returning empty mapping.")
            return {}

        topic_info = topic_model.get_topic_info() #
        
        #
        prompt = (
            "You are an expert academic researcher and librarian. "
            "I have a list of topics generated by a topic modeling algorithm from research papers. "
            "For each topic, I will provide the top 15 keywords. "
            "Your task is to create a concise, professional academic category name (2-5 words) for each topic. "
            "Respond ONLY with a valid JSON format mapping the Topic ID (string) to the generated name.\n"
            "Example: {\"0\": \"Clinical Stroke Management\", \"1\": \"Quantum Computing Algorithms\"}\n\n"
        )

        for _, row in topic_info.iterrows(): #
            topic_id = row['Topic'] #
            if topic_id == -1: #
                continue 
            
            keywords = [word for word, _ in topic_model.get_topic(topic_id)][:15] #
            rep_docs = topic_model.get_representative_docs(topic_id) #
            titles = [doc[:150] + "..." for doc in rep_docs[:3]] if rep_docs else [] #

            prompt += f"Topic ID: {topic_id}\n" #
            prompt += f"Keywords: {', '.join(keywords)}\n" #

        try:
            response = self.model.generate_content(
                prompt,
                generation_config=genai.GenerationConfig(
                    response_mime_type="application/json" #
                )
            )
            return json.loads(response.text) #
        except Exception as e:
            logger.error(f"Failed to generate LLM names: {e}")
            return {}